In [1]:
import chainer
from chainer import training, iterators, optimizers, serializers, Chain
import chainer.functions as F
import chainer.links as L
 
from chainer.training import extensions
from chainer.datasets import tuple_dataset
from chainer import optimizers, Chain, dataset, datasets, iterators
import numpy as np

In [42]:
def data_read( file_name, key, is_one_hot ):
    teachers = np.array([] )
    answers =  np.array([] )

    f = open( file_name, mode = "r" )
    f_string = f.readlines()
    data = np.array([] )
    
    for i in range( 0, len( f_string ) ):
        #引数を用いて正解ラベルを振り分ける
        if( i != 0 and i%key == 0 ):
            teachers = np.append( teachers, data)
            data = np.array([] )
            # 正解ラベルをone hotで表現する場合
            if( is_one_hot ):
                tmp_data = np.zeros(10)
                for j in f_string[i].replace( "\n", "" ):
                    tmp_data[int(j)] += 1
                answers = np.append( answers, tmp_data )
            else:
                answers = np.append( answers, float(f_string[i].replace( "\n", "" )))
        else:
            data = np.append( data, float(f_string[i].replace( "\n", "" )))
    
    f.close()
    
    teachers = teachers.astype( np.float32 )
    answers = answers.astype( np.float32 )
    
    teachers = np.reshape( teachers, ( int( len( teachers ) / key ), key ) )
    answers = np.reshape( answers, ( int( len( answers ) / 10 ) , 10 ) )

    return teachers, answers


In [43]:
teachers, answers = data_read( 'numbers.txt', 3,  )

In [46]:
print(answers[0:3])

[[1. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 0.]]
